### ISSUE TITLE
Is it possible to support the older versions of Photoshop? 

### ISSUE THREAD

**Issue by ghost** [profdl/OKColorPicker#1]
I greatly appreciate the work you have done but I'm not able to use it. I am using Photoshop CC 19 and for me this might just be the last photoshop version for lifetime. It would be far more conventient to just download it from github...put it in the plugins folder and start creating stuffs.

**Comment by profdl** [comment]
Hi! Try these files https://drive.google.com/drive/folders/1F04nXvCZnJi85pBIQLBWU7u34HX6Ec7Z?usp=sharing

**Comment by ghost** [comment]
Hey Thank you for being kind and sending the file. Long story short....I tired all the various methods to install this including the cmd but it doesnt install without CCX tools. 

Long story long...I debloat most of the softwares I use and the adobe I use are lightroom classic cc 2020, photoshop cc 2020 and indesign 2022 all for very particular reasons....like earlier indesign have no support for most laptop displays and latest indesign is getting clunky after removing the publish menu. Photoshop getting larger with AI that I dont like and Lightroom has so many unnecessary features I will never use. All of them UIs are getting slower even on a powerful machine. My only solution was to completely get rid of Creative Cloud, CCX Processes, CC LIbraries 32bit and all those unncessary services and startup entries. The result is purely enjoyable experience without worrying they might get updated or my privacy will be invaded. 

So thanks to you I have the file you sent and when i have a few days of holilday I will install it then. Right after installing Creative Cloud I will have to debloat all over again but it will be worth it. Unless you have another method to install this I will send you a reply after I have successfully installed in the near future. Have a great year.
